<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Apples-MacBook-Pro.local" failures="1" tests="2" name="Test" time="39.527" errors="0" timestamp="2024-10-03T19:25:51 IST">
  <testcase classname="com.qa.tests.SettingsTests" name="@BeforeMethod beforeMethod" time="0.003">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.tests.SettingsTests.beforeMethod(SettingsTests.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase classname="com.qa.tests.SettingsTests" name="@AfterMethod afterMethod" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase classname="com.qa.base.Basetest" name="@AfterMethod afterMethod" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase classname="com.qa.tests.LoginTests" name="successfulLogin" time="26.31">
    <failure type="java.lang.AssertionError" message="expected [null] but found [List5]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [List5]
at com.qa.tests.LoginTests.successfulLogin(LoginTests.java:95)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- successfulLogin -->
  <testcase classname="com.qa.tests.SettingsTests" name="logoutApplication" time="0.0">
    <skipped/>
  </testcase> <!-- logoutApplication -->
  <testcase classname="com.qa.base.Basetest" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase classname="com.qa.base.Basetest" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
</testsuite> <!-- Test -->
